export const mockPosts = [
  {
    id: "post1",
    jobType: "full-time",
    title: "Senior Frontend Developer",
    company: "TechCorp",
    location: "San Francisco, CA",
    salary: "$120,000 - $150,000",
    duration: "Permanent",
    description:
      "We are looking for a Senior Frontend Developer to join our team. You will be responsible for building and maintaining our web applications. The ideal candidate has experience with React, TypeScript, and modern frontend development practices.",
    skills: ["React", "TypeScript", "JavaScript", "HTML", "CSS", "Redux"],
    applicationDeadline: "2023-06-30",
    views: 245,
    applications: 12,
    createdAt: "2023-05-15",
  },
  {
    id: "post2",
    jobType: "internship",
    title: "Software Engineering Intern",
    company: "TechStart",
    location: "Remote",
    salary: "$30/hour",
    duration: "3 months",
    description:
      "Join our engineering team for a summer internship where you'll work on real projects and learn from experienced developers. This is a great opportunity to gain hands-on experience in software development.",
    skills: ["JavaScript", "React", "Node.js", "Git", "Problem Solving"],
    applicationDeadline: "2023-05-31",
    views: 189,
    applications: 24,
    createdAt: "2023-05-10",
  },
  {
    id: "post3",
    jobType: "full-time",
    title: "UX/UI Designer",
    company: "CreativeMinds",
    location: "New York, NY",
    salary: "$90,000 - $120,000",
    duration: "Permanent",
    description:
      "Join our design team to create beautiful, intuitive user experiences for our clients. You'll be responsible for the entire design process from research to implementation.",
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping", "UI Design", "Interaction Design"],
    applicationDeadline: "2023-06-15",
    views: 156,
    applications: 8,
    createdAt: "2023-05-05",
  },
  {
    id: "post4",
    jobType: "internship",
    title: "Data Science Intern",
    company: "DataMinds",
    location: "Boston, MA",
    salary: "$25/hour",
    duration: "6 months",
    description:
      "We're looking for a Data Science Intern to help us analyze data and build machine learning models. You'll work with our data science team on real-world problems and gain valuable experience in the field.",
    skills: ["Python", "Data Analysis", "Machine Learning", "Statistics", "SQL"],
    applicationDeadline: "2023-06-10",
    views: 132,
    applications: 16,
    createdAt: "2023-05-01",
  },
  {
    id: "post5",
    jobType: "full-time",
    title: "DevOps Engineer",
    company: "CloudNative",
    location: "Austin, TX",
    salary: "$130,000 - $160,000",
    duration: "Permanent",
    description:
      "We're looking for a DevOps Engineer to help us build and maintain our cloud infrastructure. You'll be responsible for automating deployments, managing our CI/CD pipelines, and ensuring system reliability.",
    skills: ["Kubernetes", "AWS", "Terraform", "Docker", "CI/CD", "Linux"],
    applicationDeadline: "2023-07-15",
    views: 98,
    applications: 6,
    createdAt: "2023-04-28",
  },
]
